system_message = "You are a logician with background in mathematics that translates natural language reasoning text to Lean code so that these natural language reasoning problems can be solved. During the translation, please keep close attention to the predicates and entities. There is an additional requirement: I also want you to try to prove the theorem you translated to Lean. If you can prove the theorem, give me True at the end of the answer. If you can prove the negation of the theorem, write False at the end of the answer. If you can neither prove whether the original theorem or the negation of the theorem, please give me Unknown at the end of the answer."
system_message = "You are a logician with background in mathematics that translates natural language reasoning text to Lean code so that these natural language reasoning problems can be solved. During the translation, please keep close attention to the predicates, the enumeration of data types and the translation of either ... or... to xor. Please also formalize the question so that all important information that's helpful to prove the theorem is captured and all information that's not helpful is omitted. There is an additional requirement: I also want you to try to prove the theorem you translated to Lean. If you can prove the theorem, give me True at the end of the answer. If you can prove the negation of the theorem, write False at the end of the answer. If you can neither prove whether the original theorem or the negation of the theorem, please give me Unknown at the end of the answer."

example_textual_input_1 = "Textual context: All people who regularly drink coffee are dependent on caffeine. People either regularly drink coffee or joke about being addicted to caffeine. No one who jokes about being addicted to caffeine is unaware that caffeine is a drug. Rina is either a student and unaware that caffeine is a drug, or neither a student nor unaware that caffeine is a drug. If Rina is not a person dependent on caffeine and a student, then Rina is either a person dependent on caffeine and a student, or neither a person dependent on caffeine nor a student.\nQuestion 1: Based on the above information, is the following statement true, false, or uncertain? Rina is a person who jokes about being addicted to caffeine or unaware that caffeine is a drug.\nQuestion 2: Based on the above information, is the following statement true, false, or uncertain? Rina is either a person who jokes about being addicted to caffeine or is unaware that caffeine is a drug.\nQuestion 3: Based on the above information, is the following statement true, false, or uncertain? Rina is either a person who regularly drinks coffee or a person who is unaware that caffeine is a drug.\nQuestion 4: Based on the above information, is the following statement true, false, or uncertain? If Rina is either a person who jokes about being addicted to caffeine and a person who is unaware that caffeine is a drug, or neither a person who jokes about being addicted to caffeine nor a person who is unaware that caffeine is a drug, then Rina jokes about being addicted to caffeine and regularly drinks coffee."

example_textual_input_2 = "Textual context: There are six types of wild turkeys: Eastern wild turkey, Osceola wild turkey, Gould’s wild turkey, Merriam’s wild turkey, Rio Grande wild turkey, and Ocellated wild turkey. Tom is not an Eastern wild turkey. Tom is not an Osceola wild turkey. Tom is also not a Gould's wild turkey, or a Merriam's wild turkey, or a Rio Grande wild turkey. Tom is a wild turkey.\nQuestion 1: Based on the above information, is the following statement true, false, or uncertain? Tom is an Ocellated wild turkey.\nQuestion 2: Based on the above information, is the following statement true, false, or uncertain? Tom is an Eastern wild turkey.\nQuestion 3: Based on the above information, is the following statement true, false, or uncertain? Joey is a wild turkey."

example_textual_input_3 = "Textual context: A La Liga soccer team ranks higher than another if it receives more points. If two La Liga soccer teams recieve the same points, the team which recieves more points from the games between the two teams ranks higher. Real Madrid and Barcelona are both La Liga soccer teams. In La Liga 2021-2022, Real Madrid recieves 86 points and Barcelon recieves 73 points. In La Liga 2021-2022, Real Madrid and Barcelona both recieve 3 points from the games between them.\nQuestion 1: Based on the above information, is the following statement true, false, or uncertain? In La Liga 2021-2022, Real Madrid ranks higher than Barcelona.\nQuestion 2: Based on the above information, is the following statement true, false, or uncertain? In La Liga 2021-2022, Barcelona ranks higher than Real Madrid."

example_outputs_True = "".join(open("output_prompt_FOLIO/FOLIO_train_True.lean").readlines())

example_outputs_False = "".join(open("output_prompt_FOLIO/FOLIO_train_False.lean").readlines())

example_outputs_Unknown = "".join(open("output_prompt_FOLIO/FOLIO_train_Unknown.lean").readlines())

example_outputs_True = "".join(open("output_prompt_FOLIO/FOLIO_train_multi_1.lean").readlines())

example_outputs_False = "".join(open("output_prompt_FOLIO/FOLIO_train_multi_2.lean").readlines())

example_outputs_Unknown = "".join(open("output_prompt_FOLIO/FOLIO_train_multi_3.lean").readlines())