[package]
name = "proofwriter_100_problem_test"
version = "0.1"
lean_version = "leanprover-community/lean:3.50.3"
# path = "proofwriter_100_problem_test"
# path = "reprover_train_FOLIO"
path = "FOLIO_30_problem_test"
